/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sae;

import sae.map.MapManager;
import sae.map.Noeud;
import sae.map.Lien;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.io.File;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileView;
import javax.swing.plaf.FileChooserUI;
import sae.myInterface.NoeudListener;

/**
 *
 * @author Loan
 */
public class Fenetre extends javax.swing.JFrame {
    
    // <editor-fold defaultstate="collapsed" desc="Déclaration">  
    
    // Model List Noeud ecran 1
    DefaultListModel<String> modelListNoeud = new DefaultListModel<>();
    
    // Model List Noeud ecran 2
    DefaultListModel<String> modelListNoeudInfo = new DefaultListModel<>();
    
    // Model List Lien ecran 1
    DefaultListModel<String> modelListLienInfo = new DefaultListModel<>();
    
    // Créer une map
    MapManager m = new MapManager();
    
    // Déclaration du sélecteur de fichier
    JFileChooser fileChooser;
    
    // Variable conserve noeud choisi ecran 2
    Noeud subPanelVoisin1tmpNoeud = null;
    
    // Variable conserve noeud choisi ecran 3
    Noeud subPanel2DAtmpNoeud = null;
    
    // Variable conserve le deuxième  noeud choisi ecran 3
    Noeud subPanel2DBtmpNoeud = null;
    
    // Déclaration du carLayout pour la gestion des ecrans
    CardLayout cardManager;
    
    // </editor-fold>

    /**
     * Creates new form Fenetre
     */
    public Fenetre() {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        initComponents();
        myinit();
        setSize(900, 700);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subPanelVoisin1 = new javax.swing.JPanel();
        labelNoeudChoisi = new javax.swing.JLabel();
        nomNoeudChoisi = new javax.swing.JLabel();
        labelTypeVoisin = new javax.swing.JLabel();
        labelListVoisin = new javax.swing.JLabel();
        choixTypeNoeud = new javax.swing.JComboBox<>();
        jScrollPane = new javax.swing.JScrollPane();
        listNoeud1 = new javax.swing.JList<>(modelListNoeud);
        sepVoisin1 = new javax.swing.JSeparator();
        labelChoixLien = new javax.swing.JLabel();
        choixLien = new javax.swing.JComboBox<>();
        labelNoeudA = new javax.swing.JLabel();
        labelNoeudB = new javax.swing.JLabel();
        nomNoeudA = new javax.swing.JLabel();
        nomNoeudB = new javax.swing.JLabel();
        subPanelVoisin2 = new javax.swing.JPanel();
        nomNoeudAP2 = new javax.swing.JLabel();
        nomNoeudBP2 = new javax.swing.JLabel();
        radioNoeudB = new javax.swing.JRadioButton();
        radioNoeudA = new javax.swing.JRadioButton();
        labelSontA2 = new javax.swing.JLabel();
        sontA2D = new javax.swing.JLabel();
        subPanelVoisinC2 = new javax.swing.JPanel();
        nomNoeudAP3 = new javax.swing.JLabel();
        nomNoeudBP3 = new javax.swing.JLabel();
        radioNoeudB2 = new javax.swing.JRadioButton();
        radioNoeudA2 = new javax.swing.JRadioButton();
        labelSontA3 = new javax.swing.JLabel();
        estPOM = new javax.swing.JLabel();
        labelSontA4 = new javax.swing.JLabel();
        choixComp = new javax.swing.JComboBox<>();
        subPanelInfo = new javax.swing.JPanel();
        colorFileLoading = new javax.swing.JPanel();
        labelFileLoading = new javax.swing.JLabel();
        colorLocating = new javax.swing.JPanel();
        labelLocating = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelAffichage = new javax.swing.JLabel();
        labelType = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        checkAffichVilles = new javax.swing.JCheckBox();
        labelNbrVilles = new javax.swing.JLabel();
        nbrVilles = new javax.swing.JLabel();
        checkAffichLoisirs = new javax.swing.JCheckBox();
        labelNbrLoisir = new javax.swing.JLabel();
        nbrLoisirs = new javax.swing.JLabel();
        checkAffichResto = new javax.swing.JCheckBox();
        labelNbrResto = new javax.swing.JLabel();
        nbrResto = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        labelNbrAutoroutes = new javax.swing.JLabel();
        nbrAutoroutes = new javax.swing.JLabel();
        labelNbrNationales = new javax.swing.JLabel();
        nbrNationales = new javax.swing.JLabel();
        nbrDepartementales = new javax.swing.JLabel();
        labelNbrDepartementales = new javax.swing.JLabel();
        checkAffichDepart = new javax.swing.JCheckBox();
        checkAffichAutoroutes = new javax.swing.JCheckBox();
        checkAffichNationales = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        labelNoeudList = new javax.swing.JLabel();
        choixTypeNoeudList = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listNoeudInfo = new javax.swing.JList<>(modelListNoeudInfo);
        jScrollPane2 = new javax.swing.JScrollPane();
        listLienInfo = new javax.swing.JList<>(modelListLienInfo);
        choixTypeLienList = new javax.swing.JComboBox<>();
        labelLienList = new javax.swing.JLabel();
        c2Group = new javax.swing.ButtonGroup();
        v2Group = new javax.swing.ButtonGroup();
        sidePanel = new javax.swing.JPanel();
        subPanelChanger = new javax.swing.JPanel();
        labelMode = new javax.swing.JLabel();
        modeChooser = new javax.swing.JComboBox<>();
        subPanelCard = new javax.swing.JPanel();
        carte = new sae.map.MapVisual();
        menuBar = new javax.swing.JMenuBar();
        menuFichier = new javax.swing.JMenu();
        itemOuvrir = new javax.swing.JMenuItem();
        menuEdition = new javax.swing.JMenu();
        itemRedispose = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        labelNoeudChoisi.setText("Noeud Choisi :");

        nomNoeudChoisi.setText("None");

        labelTypeVoisin.setText("Type :");

        labelListVoisin.setText("Voisin Direct :");

        choixTypeNoeud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ville", "Centre de loisir", "Restaurant" }));
        choixTypeNoeud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixTypeNoeudActionPerformed(evt);
            }
        });

        jScrollPane.setViewportView(listNoeud1);

        labelChoixLien.setText("Choix Lien : ");

        choixLien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixLienActionPerformed(evt);
            }
        });

        labelNoeudA.setText("Nom Noeud A :");

        labelNoeudB.setText("Nom Noeud B :");

        nomNoeudA.setText("None");

        nomNoeudB.setText("None");

        javax.swing.GroupLayout subPanelVoisin1Layout = new javax.swing.GroupLayout(subPanelVoisin1);
        subPanelVoisin1.setLayout(subPanelVoisin1Layout);
        subPanelVoisin1Layout.setHorizontalGroup(
            subPanelVoisin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelVoisin1Layout.createSequentialGroup()
                .addGroup(subPanelVoisin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelVoisin1Layout.createSequentialGroup()
                        .addGroup(subPanelVoisin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(subPanelVoisin1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(subPanelVoisin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(subPanelVoisin1Layout.createSequentialGroup()
                                        .addComponent(labelNoeudChoisi)
                                        .addGap(55, 55, 55)
                                        .addComponent(nomNoeudChoisi))
                                    .addGroup(subPanelVoisin1Layout.createSequentialGroup()
                                        .addGroup(subPanelVoisin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(choixTypeNoeud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelTypeVoisin))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(subPanelVoisin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelListVoisin)
                                            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(subPanelVoisin1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(subPanelVoisin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(subPanelVoisin1Layout.createSequentialGroup()
                                        .addComponent(labelChoixLien)
                                        .addGap(56, 56, 56)
                                        .addComponent(choixLien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(subPanelVoisin1Layout.createSequentialGroup()
                                        .addGroup(subPanelVoisin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelNoeudA)
                                            .addComponent(nomNoeudA))
                                        .addGap(38, 38, 38)
                                        .addGroup(subPanelVoisin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelNoeudB)
                                            .addComponent(nomNoeudB))))))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addComponent(sepVoisin1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        subPanelVoisin1Layout.setVerticalGroup(
            subPanelVoisin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelVoisin1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(subPanelVoisin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNoeudChoisi)
                    .addComponent(nomNoeudChoisi))
                .addGap(18, 18, 18)
                .addGroup(subPanelVoisin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTypeVoisin)
                    .addComponent(labelListVoisin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelVoisin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(choixTypeNoeud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sepVoisin1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelVoisin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelChoixLien)
                    .addComponent(choixLien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(subPanelVoisin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNoeudA)
                    .addComponent(labelNoeudB))
                .addGap(18, 18, 18)
                .addGroup(subPanelVoisin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomNoeudA)
                    .addComponent(nomNoeudB))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        nomNoeudAP2.setText("...");

        nomNoeudBP2.setText("...");

        v2Group.add(radioNoeudB);
        radioNoeudB.setText("Nom Noeud B :");
        radioNoeudB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNoeudBActionPerformed(evt);
            }
        });

        v2Group.add(radioNoeudA);
        radioNoeudA.setSelected(true);
        radioNoeudA.setText("Nom Noeud A :");
        radioNoeudA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNoeudAActionPerformed(evt);
            }
        });

        labelSontA2.setText("Sont a 2 de distance : ");

        sontA2D.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sontA2D.setText("...");

        javax.swing.GroupLayout subPanelVoisin2Layout = new javax.swing.GroupLayout(subPanelVoisin2);
        subPanelVoisin2.setLayout(subPanelVoisin2Layout);
        subPanelVoisin2Layout.setHorizontalGroup(
            subPanelVoisin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelVoisin2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(subPanelVoisin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioNoeudB)
                    .addComponent(radioNoeudA)
                    .addGroup(subPanelVoisin2Layout.createSequentialGroup()
                        .addComponent(labelSontA2)
                        .addGap(30, 30, 30)
                        .addComponent(sontA2D))
                    .addGroup(subPanelVoisin2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(subPanelVoisin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomNoeudBP2)
                            .addComponent(nomNoeudAP2))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        subPanelVoisin2Layout.setVerticalGroup(
            subPanelVoisin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelVoisin2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(radioNoeudA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomNoeudAP2)
                .addGap(30, 30, 30)
                .addComponent(radioNoeudB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomNoeudBP2)
                .addGap(35, 35, 35)
                .addGroup(subPanelVoisin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sontA2D)
                    .addComponent(labelSontA2))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        nomNoeudAP3.setText("...");

        nomNoeudBP3.setText("...");

        c2Group.add(radioNoeudB2);
        radioNoeudB2.setText("Nom Noeud B :");

        c2Group.add(radioNoeudA2);
        radioNoeudA2.setSelected(true);
        radioNoeudA2.setText("Nom Noeud A :");

        labelSontA3.setText("A est ");

        estPOM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        estPOM.setText("...");

        labelSontA4.setText("que B");

        choixComp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OUVERTE", "GASTRONOMIQUE", "CULTURELLE" }));
        choixComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixCompActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subPanelVoisinC2Layout = new javax.swing.GroupLayout(subPanelVoisinC2);
        subPanelVoisinC2.setLayout(subPanelVoisinC2Layout);
        subPanelVoisinC2Layout.setHorizontalGroup(
            subPanelVoisinC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelVoisinC2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(subPanelVoisinC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelVoisinC2Layout.createSequentialGroup()
                        .addGroup(subPanelVoisinC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioNoeudB2)
                            .addComponent(radioNoeudA2)
                            .addGroup(subPanelVoisinC2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(subPanelVoisinC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomNoeudBP3)
                                    .addComponent(nomNoeudAP3))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(subPanelVoisinC2Layout.createSequentialGroup()
                        .addComponent(labelSontA3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estPOM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(choixComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelSontA4)
                        .addGap(40, 40, 40))))
        );
        subPanelVoisinC2Layout.setVerticalGroup(
            subPanelVoisinC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelVoisinC2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(radioNoeudA2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomNoeudAP3)
                .addGap(30, 30, 30)
                .addComponent(radioNoeudB2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomNoeudBP3)
                .addGap(35, 35, 35)
                .addGroup(subPanelVoisinC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estPOM)
                    .addComponent(labelSontA3)
                    .addComponent(labelSontA4)
                    .addComponent(choixComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        colorFileLoading.setBackground(new java.awt.Color(255, 255, 255));
        colorFileLoading.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout colorFileLoadingLayout = new javax.swing.GroupLayout(colorFileLoading);
        colorFileLoading.setLayout(colorFileLoadingLayout);
        colorFileLoadingLayout.setHorizontalGroup(
            colorFileLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );
        colorFileLoadingLayout.setVerticalGroup(
            colorFileLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        labelFileLoading.setText("Chargement du Fichier");

        colorLocating.setBackground(new java.awt.Color(255, 255, 255));
        colorLocating.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout colorLocatingLayout = new javax.swing.GroupLayout(colorLocating);
        colorLocating.setLayout(colorLocatingLayout);
        colorLocatingLayout.setHorizontalGroup(
            colorLocatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        colorLocatingLayout.setVerticalGroup(
            colorLocatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        labelLocating.setText("Positionnement");

        labelAffichage.setText("Affichage");

        labelType.setText("Type");

        labelNombre.setText("Nombre");

        checkAffichVilles.setSelected(true);
        checkAffichVilles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAffichVillesActionPerformed(evt);
            }
        });

        labelNbrVilles.setText("Villes");

        nbrVilles.setText("0");

        checkAffichLoisirs.setSelected(true);
        checkAffichLoisirs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAffichLoisirsActionPerformed(evt);
            }
        });

        labelNbrLoisir.setText("Centres de Loisirs");

        nbrLoisirs.setText("0");

        checkAffichResto.setSelected(true);
        checkAffichResto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAffichRestoActionPerformed(evt);
            }
        });

        labelNbrResto.setText("Restaurants");

        nbrResto.setText("0");

        labelNbrAutoroutes.setText("Autoroutes");

        nbrAutoroutes.setText("0");

        labelNbrNationales.setText("Nationales");

        nbrNationales.setText("0");

        nbrDepartementales.setText("0");

        labelNbrDepartementales.setText("Départementales");

        checkAffichDepart.setSelected(true);
        checkAffichDepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAffichDepartActionPerformed(evt);
            }
        });

        checkAffichAutoroutes.setSelected(true);
        checkAffichAutoroutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAffichAutoroutesActionPerformed(evt);
            }
        });

        checkAffichNationales.setSelected(true);
        checkAffichNationales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAffichNationalesActionPerformed(evt);
            }
        });

        labelNoeudList.setText("Noeud");

        choixTypeNoeudList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ville", "Restaurant", "Centre de Loisir" }));
        choixTypeNoeudList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixTypeNoeudListActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listNoeudInfo);

        jScrollPane2.setViewportView(listLienInfo);

        choixTypeLienList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Autoroute", "Nationale", "Départementale" }));
        choixTypeLienList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixTypeLienListActionPerformed(evt);
            }
        });

        labelLienList.setText("Lien");

        javax.swing.GroupLayout subPanelInfoLayout = new javax.swing.GroupLayout(subPanelInfo);
        subPanelInfo.setLayout(subPanelInfoLayout);
        subPanelInfoLayout.setHorizontalGroup(
            subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelInfoLayout.createSequentialGroup()
                .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelInfoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelInfoLayout.createSequentialGroup()
                                .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(choixTypeNoeudList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNoeudList))
                                .addGap(18, 18, 18))
                            .addGroup(subPanelInfoLayout.createSequentialGroup()
                                .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(choixTypeLienList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelLienList))
                                .addGap(24, 24, 24)))
                        .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(subPanelInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(subPanelInfoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(colorFileLoading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(colorLocating, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLocating)
                            .addComponent(labelFileLoading))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelInfoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelInfoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(subPanelInfoLayout.createSequentialGroup()
                                .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(checkAffichVilles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkAffichLoisirs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkAffichResto))
                                .addGap(30, 30, 30)
                                .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(subPanelInfoLayout.createSequentialGroup()
                                        .addComponent(labelNbrResto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nbrResto))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelInfoLayout.createSequentialGroup()
                                        .addComponent(labelNbrVilles)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nbrVilles))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelInfoLayout.createSequentialGroup()
                                        .addComponent(labelNbrLoisir)
                                        .addGap(46, 46, 46)
                                        .addComponent(nbrLoisirs))))
                            .addGroup(subPanelInfoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(subPanelInfoLayout.createSequentialGroup()
                                .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(checkAffichNationales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(checkAffichDepart))
                                    .addComponent(checkAffichAutoroutes))
                                .addGap(31, 31, 31)
                                .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(subPanelInfoLayout.createSequentialGroup()
                                        .addComponent(labelNbrNationales)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nbrNationales))
                                    .addGroup(subPanelInfoLayout.createSequentialGroup()
                                        .addComponent(labelNbrAutoroutes)
                                        .addGap(75, 75, 75)
                                        .addComponent(nbrAutoroutes))
                                    .addGroup(subPanelInfoLayout.createSequentialGroup()
                                        .addComponent(labelNbrDepartementales)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nbrDepartementales))))))
                    .addGroup(subPanelInfoLayout.createSequentialGroup()
                        .addComponent(labelAffichage)
                        .addGap(18, 18, 18)
                        .addComponent(labelType)
                        .addGap(66, 66, 66)
                        .addComponent(labelNombre)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subPanelInfoLayout.setVerticalGroup(
            subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelInfoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(colorFileLoading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelFileLoading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(colorLocating, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelLocating))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(subPanelInfoLayout.createSequentialGroup()
                        .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAffichage)
                            .addComponent(labelType)
                            .addComponent(labelNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkAffichVilles, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelNbrVilles)
                                .addComponent(nbrVilles)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNbrLoisir)
                            .addComponent(nbrLoisirs)))
                    .addComponent(checkAffichLoisirs, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nbrResto)
                    .addComponent(checkAffichResto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNbrResto))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkAffichAutoroutes, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNbrAutoroutes)
                        .addComponent(nbrAutoroutes)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNbrNationales)
                        .addComponent(nbrNationales))
                    .addComponent(checkAffichNationales, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNbrDepartementales)
                        .addComponent(nbrDepartementales))
                    .addComponent(checkAffichDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelInfoLayout.createSequentialGroup()
                        .addComponent(labelNoeudList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(choixTypeNoeudList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(subPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelInfoLayout.createSequentialGroup()
                        .addComponent(labelLienList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(choixTypeLienList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SAE GRAMA");

        sidePanel.setLayout(new java.awt.BorderLayout(10, 10));

        subPanelChanger.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 10));

        labelMode.setText("Mode");

        modeChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Information", "Voisinage direct", "Voisinage à 2 sauts", "Comp à 2 >= sauts " }));
        modeChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subPanelChangerLayout = new javax.swing.GroupLayout(subPanelChanger);
        subPanelChanger.setLayout(subPanelChangerLayout);
        subPanelChangerLayout.setHorizontalGroup(
            subPanelChangerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelChangerLayout.createSequentialGroup()
                .addComponent(labelMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(modeChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        subPanelChangerLayout.setVerticalGroup(
            subPanelChangerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMode, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(modeChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        sidePanel.add(subPanelChanger, java.awt.BorderLayout.PAGE_START);

        subPanelCard.setLayout(new java.awt.CardLayout());
        sidePanel.add(subPanelCard, java.awt.BorderLayout.CENTER);

        getContentPane().add(sidePanel, java.awt.BorderLayout.EAST);

        carte.setBackground(new java.awt.Color(204, 204, 204));
        carte.setPreferredSize(new java.awt.Dimension(200, 428));

        javax.swing.GroupLayout carteLayout = new javax.swing.GroupLayout(carte);
        carte.setLayout(carteLayout);
        carteLayout.setHorizontalGroup(
            carteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        carteLayout.setVerticalGroup(
            carteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(carte, java.awt.BorderLayout.CENTER);

        menuFichier.setText("Fichier");

        itemOuvrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemOuvrir.setText("Ouvrir csv");
        itemOuvrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOuvrirActionPerformed(evt);
            }
        });
        menuFichier.add(itemOuvrir);

        menuBar.add(menuFichier);

        menuEdition.setText("Edition");

        itemRedispose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        itemRedispose.setText("Redisposer");
        itemRedispose.setEnabled(false);
        itemRedispose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRedisposeActionPerformed(evt);
            }
        });
        menuEdition.add(itemRedispose);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem1.setText("Swap");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuEdition.add(jMenuItem1);

        menuBar.add(menuEdition);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // <editor-fold defaultstate="collapsed" desc="Methode">  
    /**
     * Initialisation  des composants
     */
    private void myinit() {
        fileChooser = new JFileChooser();
        //fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        fileChooser.setCurrentDirectory(new File("D:/COUR/2022/JAVA/sae-java"));

        carte.addColorIndicator(colorLocating);
        m.addColorIndicator(colorFileLoading);

        cardManager = (CardLayout) subPanelCard.getLayout();
        subPanelCard.add(subPanelInfo, "0");
        subPanelCard.add(subPanelVoisin1, "1");
        subPanelCard.add(subPanelVoisin2, "2");
        subPanelCard.add(subPanelVoisinC2, "3");
        cardManager.first(subPanelCard);

        sontA2D.setOpaque(true);

        carte.addNoeudListener(new NoeudListener() {
            @Override
            public void noeudSelected(Noeud obj) {
                if (modeChooser.getSelectedIndex() == 1) {
                    subPanelVoisin1tmpNoeud = obj;
                    nomNoeudChoisi.setText(obj.toStringList());
                    updateListNoeudVoisn1();
                } else if (modeChooser.getSelectedIndex() == 2) {
                    if (radioNoeudA.isSelected()) {
                        subPanel2DAtmpNoeud = obj;
                        nomNoeudAP2.setText(obj.toStringList());
                        ;
                    } else {
                        subPanel2DBtmpNoeud = obj;
                        nomNoeudBP2.setText(obj.toStringList());

                    }

                    updateEstA2D();

                } else if (modeChooser.getSelectedIndex() == 3) {
                    if (radioNoeudA2.isSelected()) {
                        subPanel2DAtmpNoeud = obj;
                        nomNoeudAP3.setText(obj.toStringList());
                    } else {
                        subPanel2DBtmpNoeud = obj;
                        nomNoeudBP3.setText(obj.toStringList());
                    }
                    updateEstPO();

                }

            }
        });

    }
    
    /**
     * Gestion combo box comparaison ouverture
     */
    private void updateEstPO() {
        if (subPanel2DAtmpNoeud != null && subPanel2DBtmpNoeud != null) {
            int res;
            estPOM.setText("plus");
            switch (choixComp.getSelectedIndex()) {
                case 0:
                    res = m.estPlusOuvert(subPanel2DAtmpNoeud, subPanel2DBtmpNoeud) == false ? 0 : 1;
                    res = m.villeNoeuds(subPanel2DAtmpNoeud) == m.villeNoeuds(subPanel2DBtmpNoeud) ? 2 : res;
                    break;
                case 1:
                    res = m.estPlusGastronomique(subPanel2DAtmpNoeud, subPanel2DBtmpNoeud) == false ? 0 : 1;
                    res = m.gastronomoieNoeuds(subPanel2DAtmpNoeud) == m.gastronomoieNoeuds(subPanel2DBtmpNoeud) ? 2 : res;
                    break;
                case 2:
                    res = m.estPlusCulturel(subPanel2DAtmpNoeud, subPanel2DBtmpNoeud) == false ? 0 : 1;
                    res = m.cultureNoeuds(subPanel2DAtmpNoeud) == m.cultureNoeuds(subPanel2DBtmpNoeud) ? 2 : res;
                    break;
                default:

                    res = 0;

            }

            if (res == 0) {
                estPOM.setText("moins");

            } else if (res == 2) {
                estPOM.setText("autant");
            }

        }

    }

    /**
     * Gestion graphique comparaison a 2 de distances
     */
    private void updateEstA2D() {
        if (subPanel2DAtmpNoeud != null && subPanel2DBtmpNoeud != null) {
            sontA2D.setBackground(Color.red);
            if (m.estA2Distance(subPanel2DAtmpNoeud, subPanel2DBtmpNoeud)) {
                sontA2D.setBackground(Color.green);
            }

            sontA2D.setText(String.valueOf(m.estA2Distance(subPanel2DAtmpNoeud, subPanel2DBtmpNoeud)));
        }
    }
    
    /**
     * Met à jour la liste de noeud voisin sur l'ecran 1
     */
    private void updateListNoeudVoisn1() {
        if (subPanelVoisin1tmpNoeud != null) {

            String slectedType = ((String) choixTypeNoeud.getSelectedItem()).equals("Ville")
                    ? "V" : (String) choixTypeNoeud.getSelectedItem();
            slectedType = choixTypeNoeud.getSelectedItem().equals("Restaurant")
                    ? "R" : slectedType;
            slectedType = choixTypeNoeud.getSelectedItem().equals("Centre de loisir")
                    ? "L" : slectedType;

            System.out.println("\u001B[32m"+"[INFO]"+"\u001B[0m"+" Type selected " +slectedType);
            modelListNoeud.removeAllElements();
            for (Noeud i : subPanelVoisin1tmpNoeud.getVoisin()) {

                if (i.getType().equals(slectedType)) {
                    modelListNoeud.addElement(i.toStringList());
                }
            }
        }
    }
    
    /**
     * Met à jour la liste de noeud sur l'ecran 0
     */
    private void updateListNoeudInfo() {
        String slectedType = ((String) choixTypeNoeudList.getSelectedItem()).equals("Ville")
                ? "V" : (String) choixTypeNoeudList.getSelectedItem();
        slectedType = choixTypeNoeudList.getSelectedItem().equals("Restaurant")
                ? "R" : slectedType;
        slectedType = choixTypeNoeudList.getSelectedItem().equals("Centre de loisir")
                ? "L" : slectedType;

        modelListNoeudInfo.removeAllElements();
        for (Noeud i : m.getListeNoeuds()) {

            if (i.getType().equals(slectedType)) {
                modelListNoeudInfo.addElement(i.toStringList());
            }
        }

    }
    
    /**
     * Met à jour la liste de lien sur l'ecran 0
     */
    private void updateListLienInfo() {
        String slectedType = ((String) choixTypeLienList.getSelectedItem()).equals("Autoroute")
                ? "A" : (String) choixTypeLienList.getSelectedItem();
        slectedType = choixTypeLienList.getSelectedItem().equals("Nationale")
                ? "N" : slectedType;
        slectedType = choixTypeLienList.getSelectedItem().equals("Départementale")
                ? "D" : slectedType;

        modelListLienInfo.removeAllElements();
        for (Lien i : m.getlisteLiens()) {

            if (i.getTypeLiens().equals(slectedType)) {
                modelListLienInfo.addElement(i.toString());
            }
        }

    }
    
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Action Performed">  
    private void itemOuvrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOuvrirActionPerformed

        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {

            itemRedispose.setEnabled(true);
            File selectedFile = fileChooser.getSelectedFile();
            m.loadMap(selectedFile.getAbsolutePath());
            carte.setToDraw(m.getListeNoeuds());
            carte.setToDrawLiens(m.getlisteLiens());
            Thread newThread = new Thread(() -> {
                carte.init();
            });
            newThread.start();
            nbrLoisirs.setText(Integer.toString(m.getNbLoisirs()));
            nbrVilles.setText(Integer.toString(m.getNbVilles()));
            nbrResto.setText(Integer.toString(m.getNbRestaurants()));

            nbrAutoroutes.setText(Integer.toString(m.getNbAutoroutes()));
            nbrNationales.setText(Integer.toString(m.getNbNationales()));
            nbrDepartementales.setText(Integer.toString(m.getNbDepartementales()));

            choixLien.setModel(new DefaultComboBoxModel<Lien>(m.getlisteLiens().toArray(new Lien[0])));
            if (choixLien.getSelectedItem() != null){
                nomNoeudAP2.setText(((Lien) choixLien.getSelectedItem()).getNoeuds1().toStringList());
                nomNoeudBP2.setText(((Lien) choixLien.getSelectedItem()).getNoeuds2().toStringList());

            }
            
            updateListNoeudInfo();
            updateListLienInfo();
        }
    }//GEN-LAST:event_itemOuvrirActionPerformed

    private void itemRedisposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRedisposeActionPerformed

        carte.init();

    }//GEN-LAST:event_itemRedisposeActionPerformed

    private void modeChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeChooserActionPerformed

        cardManager.show(subPanelCard, Integer.toString(modeChooser.getSelectedIndex()));


    }//GEN-LAST:event_modeChooserActionPerformed

    private void checkAffichVillesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAffichVillesActionPerformed

        carte.setTypeToDraw("V", checkAffichVilles.isSelected());
    }//GEN-LAST:event_checkAffichVillesActionPerformed

    private void checkAffichLoisirsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAffichLoisirsActionPerformed
        carte.setTypeToDraw("L", checkAffichLoisirs.isSelected());
    }//GEN-LAST:event_checkAffichLoisirsActionPerformed

    private void checkAffichRestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAffichRestoActionPerformed
        carte.setTypeToDraw("R", checkAffichResto.isSelected());
    }//GEN-LAST:event_checkAffichRestoActionPerformed

    private void checkAffichDepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAffichDepartActionPerformed
        carte.setTypeToDrawLiens("D", checkAffichDepart.isSelected());
    }//GEN-LAST:event_checkAffichDepartActionPerformed

    private void checkAffichAutoroutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAffichAutoroutesActionPerformed
        carte.setTypeToDrawLiens("A", checkAffichAutoroutes.isSelected());
    }//GEN-LAST:event_checkAffichAutoroutesActionPerformed

    private void checkAffichNationalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAffichNationalesActionPerformed
        carte.setTypeToDrawLiens("N", checkAffichNationales.isSelected());
    }//GEN-LAST:event_checkAffichNationalesActionPerformed

    private void choixTypeNoeudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixTypeNoeudActionPerformed
        updateListNoeudVoisn1();
    }//GEN-LAST:event_choixTypeNoeudActionPerformed

    private void choixLienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixLienActionPerformed
        nomNoeudA.setText(((Lien) choixLien.getSelectedItem()).getNoeuds1().toStringList());
        nomNoeudB.setText(((Lien) choixLien.getSelectedItem()).getNoeuds2().toStringList());
    }//GEN-LAST:event_choixLienActionPerformed

    private void choixCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixCompActionPerformed
        updateEstPO();
    }//GEN-LAST:event_choixCompActionPerformed

    private void choixTypeNoeudListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixTypeNoeudListActionPerformed
        updateListNoeudInfo();
    }//GEN-LAST:event_choixTypeNoeudListActionPerformed

    private void choixTypeLienListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixTypeLienListActionPerformed
        updateListLienInfo();
    }//GEN-LAST:event_choixTypeLienListActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        carte.swap();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void radioNoeudAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNoeudAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNoeudAActionPerformed

    private void radioNoeudBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNoeudBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNoeudBActionPerformed

    // </editor-fold>
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */


 /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup c2Group;
    private sae.map.MapVisual carte;
    private javax.swing.JCheckBox checkAffichAutoroutes;
    private javax.swing.JCheckBox checkAffichDepart;
    private javax.swing.JCheckBox checkAffichLoisirs;
    private javax.swing.JCheckBox checkAffichNationales;
    private javax.swing.JCheckBox checkAffichResto;
    private javax.swing.JCheckBox checkAffichVilles;
    private javax.swing.JComboBox<String> choixComp;
    private javax.swing.JComboBox<Lien> choixLien;
    private javax.swing.JComboBox<String> choixTypeLienList;
    private javax.swing.JComboBox<String> choixTypeNoeud;
    private javax.swing.JComboBox<String> choixTypeNoeudList;
    private javax.swing.JPanel colorFileLoading;
    private javax.swing.JPanel colorLocating;
    private javax.swing.JLabel estPOM;
    private javax.swing.JMenuItem itemOuvrir;
    private javax.swing.JMenuItem itemRedispose;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelAffichage;
    private javax.swing.JLabel labelChoixLien;
    private javax.swing.JLabel labelFileLoading;
    private javax.swing.JLabel labelLienList;
    private javax.swing.JLabel labelListVoisin;
    private javax.swing.JLabel labelLocating;
    private javax.swing.JLabel labelMode;
    private javax.swing.JLabel labelNbrAutoroutes;
    private javax.swing.JLabel labelNbrDepartementales;
    private javax.swing.JLabel labelNbrLoisir;
    private javax.swing.JLabel labelNbrNationales;
    private javax.swing.JLabel labelNbrResto;
    private javax.swing.JLabel labelNbrVilles;
    private javax.swing.JLabel labelNoeudA;
    private javax.swing.JLabel labelNoeudB;
    private javax.swing.JLabel labelNoeudChoisi;
    private javax.swing.JLabel labelNoeudList;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelSontA2;
    private javax.swing.JLabel labelSontA3;
    private javax.swing.JLabel labelSontA4;
    private javax.swing.JLabel labelType;
    private javax.swing.JLabel labelTypeVoisin;
    private javax.swing.JList<String> listLienInfo;
    private javax.swing.JList<String> listNoeud1;
    private javax.swing.JList<String> listNoeudInfo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEdition;
    private javax.swing.JMenu menuFichier;
    private javax.swing.JComboBox<String> modeChooser;
    private javax.swing.JLabel nbrAutoroutes;
    private javax.swing.JLabel nbrDepartementales;
    private javax.swing.JLabel nbrLoisirs;
    private javax.swing.JLabel nbrNationales;
    private javax.swing.JLabel nbrResto;
    private javax.swing.JLabel nbrVilles;
    private javax.swing.JLabel nomNoeudA;
    private javax.swing.JLabel nomNoeudAP2;
    private javax.swing.JLabel nomNoeudAP3;
    private javax.swing.JLabel nomNoeudB;
    private javax.swing.JLabel nomNoeudBP2;
    private javax.swing.JLabel nomNoeudBP3;
    private javax.swing.JLabel nomNoeudChoisi;
    private javax.swing.JRadioButton radioNoeudA;
    private javax.swing.JRadioButton radioNoeudA2;
    private javax.swing.JRadioButton radioNoeudB;
    private javax.swing.JRadioButton radioNoeudB2;
    private javax.swing.JSeparator sepVoisin1;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel sontA2D;
    private javax.swing.JPanel subPanelCard;
    private javax.swing.JPanel subPanelChanger;
    private javax.swing.JPanel subPanelInfo;
    private javax.swing.JPanel subPanelVoisin1;
    private javax.swing.JPanel subPanelVoisin2;
    private javax.swing.JPanel subPanelVoisinC2;
    private javax.swing.ButtonGroup v2Group;
    // End of variables declaration//GEN-END:variables
}
